export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './feeds.service';
import { FeedsService } from './feeds.service';
export * from './feeds.serviceInterface';
export * from './posts.service';
import { PostsService } from './posts.service';
export * from './posts.serviceInterface';
export * from './subscribtions.service';
import { SubscribtionsService } from './subscribtions.service';
export * from './subscribtions.serviceInterface';
export * from './topics.service';
import { TopicsService } from './topics.service';
export * from './topics.serviceInterface';
export * from './users.service';
import { UsersService } from './users.service';
export * from './users.serviceInterface';
export const APIS = [AuthService, FeedsService, PostsService, SubscribtionsService, TopicsService, UsersService];
