/**
 * MDD OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuthInfo } from '../model/models';
import { JwtInfo } from '../model/models';
import { NewUser } from '../model/models';
import { ResponseMessage } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Login an existing user
     * 
     * @param authInfo 
     */
    login(authInfo: AuthInfo, extraHttpRequestParams?: any): Observable<JwtInfo>;

    /**
     * Register a new User
     * 
     * @param newUser 
     */
    register(newUser: NewUser, extraHttpRequestParams?: any): Observable<ResponseMessage>;

}
