/**
 * MDD OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Post } from '../model/models';
import { ResponseMessage } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FeedsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get the Posts from the user\&#39;s feed
     * 
     * @param userid 
     * @param sort Sort order
     */
    getUserFeed(userid: number, sort?: 'asc' | 'desc', extraHttpRequestParams?: any): Observable<Array<Post>>;

}
