/**
 * MDD OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ResponseMessage } from '../model/models';
import { Topic } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SubscribtionsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get user\&#39;s subscribtions
     * 
     * @param userid 
     */
    getUserSubscribtions(userid: number, extraHttpRequestParams?: any): Observable<Array<Topic>>;

    /**
     * Subscribe User to Topic
     * 
     * @param userid 
     * @param ref 
     */
    subscribeToTopic(userid: number, ref: string, extraHttpRequestParams?: any): Observable<ResponseMessage>;

    /**
     * Unsubscribe User to Topic
     * 
     * @param userid 
     * @param ref 
     */
    unsubscribe(userid: number, ref: string, extraHttpRequestParams?: any): Observable<ResponseMessage>;

}
