/**
 * MDD OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ResponseMessage } from '../model/models';
import { Topic } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TopicsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get all topics
     * 
     */
    getAllTopics(extraHttpRequestParams?: any): Observable<Array<Topic>>;

    /**
     * Get a Topic by its ref
     * 
     * @param ref 
     */
    getTopicByRef(ref: string, extraHttpRequestParams?: any): Observable<Topic>;

}
