/**
 * MDD OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ResponseMessage } from '../model/models';
import { User } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get a User by its id
     * 
     * @param id 
     */
    getUserById(id: number, extraHttpRequestParams?: any): Observable<User>;

    /**
     * Update the User with id
     * 
     * @param id 
     * @param user 
     */
    updateUserById(id: number, user?: User, extraHttpRequestParams?: any): Observable<User>;

}
