spring:
  application:
    name:api-gateway
  cloud:
    gateway:
      routes:
      - id: topics_route
        uri: http://localhost:8081
        predicates:
        - Path=/api/topics/**
      - id: auth_route
        uri: http://localhost:8088
        predicates:
        - Path=/api/auth/**
management:
  endpoints:
    web:
      exposure:
        include: "*"