spring:
  application:
    name:api-gateway
  cloud:
    gateway:
      routes:
      - id: topics_route
        uri: http://localhost:8081
        predicates:
        - Path=/api/topics/**
management:
  endpoints:
    web:
      exposure:
        include: "*"